export const CREATE_CAMPAIGN_SUCCESS = "CREATE_CAMPAIGN_SUCCESS";
export const CREATE_CAMPAIGN = "CREATE_CAMPAIGN_SUCCESS";
export const LOAD_CAMPAIGNS_SUCCESS = "LOAD_CAMPAIGN_SUCCESS";
export const UPDATE_CAMPAIGN_SUCCESS = "UPDATE_CAMPAIGN_SUCCESS";
export const CREATE_DUNGEON_SUCCESS = "CREATE_DUNGEON_SUCCESS";
export const LOAD_DUNGEONS_SUCCESS = "LOAD_DUNGEONS_SUCCESS";